"""create ai tables

Revision ID: 95fe228d1010
Revises: 
Create Date: 2026-04-11 03:30:32.754974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '95fe228d1010'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_hit', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_cache_cache_key'), 'ai_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_ai_cache_expires_at'), 'ai_cache', ['expires_at'], unique=False)
    op.create_table('book_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chapter_title', sa.String(length=500), nullable=True),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('child_text', sa.Text(), nullable=False),
    sa.Column('parent_text', sa.Text(), nullable=False),
    sa.Column('child_token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=False),
    sa.Column('search_vector', pg.TSVECTOR(), sa.Computed("to_tsvector('english', child_text)", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # HNSW on 3072-dim vectors uses halfvec expression index (see migration 73af8b5007a4)
    op.create_index('idx_book_chunks_search_vector', 'book_chunks', ['search_vector'], unique=False, postgresql_using='gin', postgresql_ops={'search_vector': 'tsvector_ops'})
    op.create_index(op.f('ix_book_chunks_book_id'), 'book_chunks', ['book_id'], unique=False)
    op.create_table('book_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('book_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('chapter_title', sa.String(length=500), nullable=True),
    sa.Column('chapter_index', sa.Integer(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_summaries_book_id'), 'book_summaries', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_summaries_book_id'), table_name='book_summaries')
    op.drop_table('book_summaries')
    op.drop_index(op.f('ix_book_chunks_book_id'), table_name='book_chunks')
    op.drop_index('idx_book_chunks_search_vector', table_name='book_chunks', postgresql_using='gin')
    op.drop_table('book_chunks')
    op.drop_index(op.f('ix_ai_cache_expires_at'), table_name='ai_cache')
    op.drop_index(op.f('ix_ai_cache_cache_key'), table_name='ai_cache')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
